### ISSUE TITLE
Still alive and well? Which modems are supported?

### ISSUE THREAD

**Issue by chmac** [darylturner/smsd#1]
Thanks for releasing this code, looks cool. Is the project still alive and well, I see the last commit was a few years ago, but maybe everything is working perfectly!

Any suggestions / list on what modems would work with this code?

**Comment by darylturner** [comment]
Hi, I've not personally used this in quite a while honestly.
It worked fine with my wavecom external modem at the time and I don't remember running into any issues with it.
Feel free to give it a try and fork the project if it helps.

**Comment by chmac** [comment]
@darylturner Awesome, thanks for the info.

I since found aa.net.uk who I can port my UK mobile number to, and then they handle all the tech stuff, I just pay a small monthly fee, so I'm gonna go that way, but will keep this in mind for other networks / countries. 👍
